name: test-tests
on: push
jobs: 
  my-job:
    runs-on: ububtu-latest
    steps:
      - name: copy-files
        uses: actions/checkout@v3
      - run: make setup
      - run: make test
      - run: make lint